# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:
  - board: nice_nano_v2
    shield: splitkb_aurora_sofle_left nice_view_adapter nice_view_battery
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n # needed for dongle
    tags: sofle dongle left
    artifact-name: periperial-left
  - board: nice_nano_v2
    shield: splitkb_aurora_sofle_right nice_view_adapter nice_view_battery
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n # needed for dongle
    tags: sofle dongle right
    artifact-name: periperial-right
  
  - board: nice_nano_v2
    shield: settings_reset
    tags: sofle reset
    artifact-name: peripherial-reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
    tags: sofle dongle reset
    artifact-name: dongle-reset
  
  - board: seeeduino_xiao_ble
    shield: splitkb_aurora_sofle_dongle prospector_adapter
    snippet: zmk-usb-logging
    cmake-args: -DEXTRA_DTC_OVERLAY_FILE="${PWD}/config/secrets.dtsi"
    tags: sofle dongle dongle_central
    artifact-name: dongle
