

CONFIG_ZMK_KEYBOARD_NAME="Sofle left"
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

CONFIG_ZMK_DISPLAY=n

CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y

CONFIG_ZMK_PIMORONI_PIM447=y
CONFIG_ZMK_PIM447_BEHAVIORS=y
# CONFIG_ZMK_PIMORONI_PIM447_AUTOMOUSE_TIMEOUT_MS=1000