
# Another thing to enable in case of BT issues (disables 2m PHY)
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Enables BT Secure Connection passkey entry and allows overwriting keys from previously paired hosts
CONFIG_ZMK_BLE_EXPERIMENTAL_SEC=y

# Decrease BT latency
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6

# increase bt power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Experimental eager debounce, caused double keypresses on BT for me..
# CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=0

# workaround for some windows bug with battery notifications
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# Uncomment these two line to add support for encoders to your firmware
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_ZMK_EXT_POWER=n

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=15000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
# # testing display sleep
# # CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=16000

CONFIG_ZMK_MOUSE=y

# Nice View battery widget (https://github.com/infely/nice-view-battery), set inverted colors
# CONFIG_NICE_VIEW_WIDGET_INVERTED=n

# CONFIG_PROSPECTOR_DISPLAY_SLEEP=y
# CONFIG_PROSPECTOR_SLEEP_DEBOUNCE_MS=600
# CONFIG_PROSPECTOR_LAYER_ROLLER_ALL_CAPS=y

CONFIG_ZMK_BLE=y
CONFIG_INPUT_INIT_PRIORITY=62
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_USB_DEVICE_HID=y

CONFIG_FPU=y

#
# Logging
#
CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_LOGGING=y
CONFIG_ZMK_LOGGING_MINIMAL=n
CONFIG_PS2_LOG_LEVEL_DBG=y
CONFIG_I2C_LOG_LEVEL_DBG=y
CONFIG_UART_LOG_LEVEL_DBG=n
CONFIG_LOG_MODE_IMMEDIATE=n

# CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_LOG_MODE_DEFERRED=n
CONFIG_LOG_PROCESS_THREAD=y
CONFIG_LOG_PROCESS_THREAD_SLEEP_MS=100
CONFIG_INPUT_LOG_LEVEL_DBG=y

# This setting is important to get the full log instead of
# one where the initial parts are cut out
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=3000
