manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: nickconway
      url-base: https://github.com/nickconway
    - name: urob
      url-base: https://github.com/urob
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: infely                             # for nice-view-battery
      url-base: https://github.com/infely
  projects:
    # - name: zmk
    #   remote: zmkfirmware
    #   revision: main
    #   import: app/west.yml
    # - name: zmk
    #   remote: nickconway
    #   revision: dev
    #   import: app/west.yml
    - name: zmk
      remote: urob
      revision: main
      import: app/west.yml
    # - name: zmk
    #   remote: petejohanson
    #   revision: feat/pointers-move-scroll
    #   import: app/west.yml
    - name: nice-view-battery
      remote: infely
      revision: main
  self:
    path: config
