# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

CONFIG_ZMK_DISPLAY=y
# CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# Nice View battery widget (https://github.com/infely/nice-view-battery), set inverted colors
CONFIG_NICE_VIEW_WIDGET_INVERTED=n

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=15000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000